addpath('C:\EEGFMRI\hmm\R01_rerun\03_code\matlab');
P = r01_params();

tag = sprintf('ICRej%02d', round(100 * P.ic_reject_threshold));  % matches your prune tag scheme

r01_eeg_runlevel_qc_gates( ...
    P.raw.eeg_eeglab, ...
    P.deriv.eeg_ic_pruned, ...
    P.qc.tables, ...
    P.qc.exclusions, ...
    'tag', tag, ...
    'overwrite', true);

