% r01_batch_export_parcel_pc_driver_v3.m
% Driver for v3 exporter (supports 3-component volume kernels).

fprintf('Driver started: %s\n', datestr(now));
fprintf('pop_loadset: %s\n', which('pop_loadset'));
fprintf('writeNPY   : %s\n', which('writeNPY'));

protocolRoot = 'C:\brainstorm_db\eegfmri_R01_ICRej70';
outDir      = 'C:\EEGFMRI\hmm\R01_rerun\02_derivatives\eeg_source\parcel_pc1';
eegCleanDir = 'C:\EEGFMRI\hmm\R01_rerun\02_derivatives\eeg_source\ic_pruned\clean';

scoutFilename = 'scout_Schaefer2018_200_7N_dilated_MNI.mat';

batch = r01_batch_export_eeg_parcel_pc_v3(protocolRoot, outDir, ...
    'EEGCleanDir', eegCleanDir, ...
    'KernelPattern', 'results_MN_EEG_KERNEL_*.mat', ...
    'DescTag', 'desc-ICRej70', ...
    'ScoutFilename', scoutFilename, ...
    'ExpectedNScouts', 200, ...
    'StrictTessMatch', true, ...
    'MinVertices', 40, ...
    'NumPC', 2, ...
    'SavePC2', true, ...
    'SignConvention', 'maxabs', ...
    'BlockSize', 0, ...
    'Overwrite', true, ...
    'Verbose', true, ...
    'GainNorm', true, ...
    'GainCap', [0, Inf], ...
    'WriteNPY', true, ...
    'ScaleChunkRows', 20000, ...
    'ContinueOnFail', false);

fprintf('\nDONE.\nGain summary: %s\nCoverage summary: %s\nManifest: %s\n', ...
    batch.gainCsv, batch.coverageCsv, batch.manifestCsv);
