protocolRoot = 'C:\brainstorm_db\eegfmri_R01_ICRej70';
T = r01_batch_make_volgrid_scouts_from_tess(protocolRoot, ...
    'scout_Schaefer2018_200_7N_dilated_MNI.mat', ...
    'atlas-Schaefer2018_desc-200Parcels7Networks', ...
    'results_MN_EEG_KERNEL_*.mat');
writetable(T, fullfile(protocolRoot, 'anat', 'batch_volgrid_scout_build.csv'));
