addpath('C:\EEGFMRI\hmm\R01_rerun\03_code\matlab');
P = r01_params();

r01_eeg_iclabel_prune_and_metadata( ...
  P.raw.eeg_eeglab, ...
  P.deriv.eeg_ic_pruned, ...
  P.qc.tables, ...
  'ic_policy', P.ic_policy, ...
  'reject_threshold', P.ic_reject_threshold, ...
  'reject_classes', P.ic_reject_classes, ...
  'threshold', P.iclabel_brain_threshold, ... % unused unless policy="brain_threshold"
  'overwrite', P.overwrite, ...
  'save_iclabel_tables', true, ...
  'save_withICA', true, ...
  'save_clean', true, ...
  'clean_remove_iclabel', true, ...
  'file_pattern', '*.set');
