addpath('C:\EEGFMRI\hmm\R01_rerun\03_code\matlab');
P = r01_params();

r01_batch_export_bst_exclusions_Fevents( ...
  P.brainstorm.db_root, ...
  P.deriv.masks_bst_exports, ...
  'overwrite', P.overwrite, ...
  'file_filter', char(P.file_filter), ...
  'recursive', true);
