addpath('C:\EEGFMRI\hmm\R01_rerun\03_code\matlab');
P = r01_params();

r01_qc_excl_union_folder( ...
  P.deriv.masks_bst_exports, ...
  P.qc.exclusions, ...
  'bst_db_root', char(P.brainstorm.db_root), ...
  'max_excl_frac_warn', P.qc.excl.max_excl_frac_warn, ...
  'max_interval_sec_warn', P.qc.excl.max_interval_sec_warn, ...
  'min_interval_sec_warn', P.qc.excl.min_interval_sec_warn);
