function [QC, MAN, EXC] = r01_eeg_runlevel_qc_gates(root_raw_eeglab, eeg_ic_pruned_dir, qc_tables_dir, qc_exclusions_dir, varargin)
%R01_EEG_RUNLEVEL_QC_GATES Legacy compatibility wrapper.
%
% The active Stage-1 scientific implementation now lives in:
%   notebooks/1_eeg_sensor/helpers/build_runlevel_qc_gates.m
%
% This preserved file remains only so older provenance callers still run.

[QC, MAN, EXC] = build_runlevel_qc_gates( ...
    root_raw_eeglab, ...
    eeg_ic_pruned_dir, ...
    qc_tables_dir, ...
    qc_exclusions_dir, ...
    varargin{:});

end
